// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fiiApi.Data;

#nullable disable

namespace fiiApi.Migrations
{
    [DbContext(typeof(FiiApiContext))]
    [Migration("20250124142319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("fiiApi.Models.FundoImobiliario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DY")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("LiquidezDiaria")
                        .HasColumnType("int");

                    b.Property<decimal>("PV")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Variacao12Meses")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("FundosImobiliarios");
                });
#pragma warning restore 612, 618
        }
    }
}
