// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fiiApi.Data;

#nullable disable

namespace fiiApi.Migrations
{
    [DbContext(typeof(FiiApiContext))]
    [Migration("20250220164836_AddInvestidor")]
    partial class AddInvestidor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FundoImobiliarioInvestidor", b =>
                {
                    b.Property<int>("CarteiraId")
                        .HasColumnType("int");

                    b.Property<int>("InvestidoresId")
                        .HasColumnType("int");

                    b.HasKey("CarteiraId", "InvestidoresId");

                    b.HasIndex("InvestidoresId");

                    b.ToTable("InvestidorFundos", (string)null);
                });

            modelBuilder.Entity("fiiApi.Models.FundoImobiliario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DY")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("LiquidezDiaria")
                        .HasColumnType("int");

                    b.Property<decimal>("PV")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Variacao12Meses")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("FundosImobiliarios");
                });

            modelBuilder.Entity("fiiApi.Models.Investidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Investidores");
                });

            modelBuilder.Entity("FundoImobiliarioInvestidor", b =>
                {
                    b.HasOne("fiiApi.Models.FundoImobiliario", null)
                        .WithMany()
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fiiApi.Models.Investidor", null)
                        .WithMany()
                        .HasForeignKey("InvestidoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
